import = [
    "~/.config/alacritty/themes/gruvbox_material_medium_dark.toml"
]

[font]
size = 12.0

[font.bold]
family = "Victor Mono"
style = "Bold"

[font.bold_italic]
family = "Victor Mono"
style = "Bold Italic"

[font.italic]
family = "Victor Mono"
style = "Italic"

[font.normal]
family = "Victor Mono"
style = "Regular"

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
decorations = 'none'
startup_mode = 'Fullscreen'

[mouse]
hide_when_typing = true
